### ISSUE TITLE
Second goal don't disappear

### ISSUE THREAD

**Issue by DevBNM** [Unity-Technologies/arfoundation-demos#3]
Hello, 

When you reach the second goal before the first goal fade off (or the second fade on), the instruction don't disappear.
It's a little issue but it can be disturbing for the users. 

Best,
Alexis

**Comment by DanMillerDev** [comment]
Thanks for the bug report, it should be fixed with this commit https://github.com/Unity-Technologies/arfoundation-demos/commit/18515c6c235406a09ff8c1f5332f6d146cf18aac
