### ISSUE TITLE
Shadow shader visble when camera moved outside of object.

### ISSUE THREAD

**Issue by rvegele** [Unity-Technologies/arfoundation-demos#32]
After placing an object on a plane the object has a nice shadow and the plane is invisible. 

But as soon as the phone (camera) is moved, and the object is no longer visible, the 'shadown plane' becomes gray and semi-transparent.

The blue sphere image shows the plane under invisible with a blurred shadow, whereas the second image shows a white wall and a dark-gray plane (changed to be more visible than the one under the blue sphere).

![IMG_6854](https://user-images.githubusercontent.com/8513898/91185152-bfef7380-e6ed-11ea-88e3-ded43255edfa.PNG)
![IMG_6855](https://user-images.githubusercontent.com/8513898/91185208-d09fe980-e6ed-11ea-8df2-202491fa8a8b.PNG)

**Comment by DanMillerDev** [comment]
@rvegele an you provide more clarification or a video of what's happening? It's hard to tell exactly what the plane or shadow object is in the second video.

**Comment by LandonTownsendUnity** [comment]
I reproduced the problem and am giving Dan a fix, no worries.

**Comment by rvegele** [comment]
> @rvegele an you provide more clarification or a video of what's happening? It's hard to tell exactly what the plane or shadow object is in the second video.

Sorry for a lacking explanation and a worse image. I believe it might not be needed any more 👍 

Thanks for the great work!

**Comment by DanMillerDev** [comment]
fixed in https://github.com/Unity-Technologies/arfoundation-demos/commit/05ff22ee67d274e1e690ccda50b2719499eb9c0a
