### ISSUE TITLE
IOS - Guidance UI Graphic Raycaster interferes with Worldspace Canvas UI Buttons in a scene

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/arfoundation-demos#35]
So I made a demo project a short while ago using the demos repo here, I liked the guidance UI. We were spawning a prefab with worldspace UI Canvas + buttons on it from an image marker.

On Android 10 devices the buttons work fine, but on IOS 13+ devices, the buttons are intermittently interactable **due to the screen space canvas having a graphic raycaster on it**

I have created a reproduction project in 2020.2.0b10 and reported the bug in the bug case below so you can see for yourself but it was easy to recreate by using the UI guidance sample and adding a spawned gameobject in the scene with worldspace canvas ui + buttons to try to press.

(Case 1291989) [UI][AR Foundation] Worldspace UI buttons work fine on Android but intermittently on IOS while in AR

>**The fix was to remove/disable the graphic raycaster from the Guidance Canvas, I think this issue may be IOS specific?** <

**Comment by DanMillerDev** [comment]
Thanks for the report, I'll look into this. I've also had some issues with graphics raycast blockers in other projects.

**Comment by ROBYER1** [comment]
Thanks Dan, it's become an issue for an app I have in development as I cannot have an Exit or Return to Menu button on the screen always. As my current workaround is to hide/unhide the screen space UI when it is needed, I can't have it always showing.

I hope there is a resolution for this issue from the QA case I referenced.

**Comment by DanMillerDev** [comment]
It looks like the issue is still being reviewed by QA, either way I've removed the graphic raycaster from the screenspace UI canvas since there aren't any buttons to click or elements to raycast against. 

https://github.com/Unity-Technologies/arfoundation-demos/commit/9a9b718d00edbeb65fead0a4999b9b5da076170a

Thanks for flagging this.
