### ISSUE TITLE
Which unity version wireframe shader work?

### ISSUE THREAD

**Issue by orangeagain** [Unity-Technologies/arfoundation-demos#38]
wireframe shader disabled on unity 2020.2 and 2019.4.
Is this funtion still ablity?

**Comment by DanMillerDev** [comment]
it should be available in both of those versions of the editor. It requires URP to be enabled. Looking into this, thanks for the report.

**Comment by DanMillerDev** [comment]
I was able to build and have the wireframe shader work correctly in 2019.4.4f1 and 2020.2.0b3, the wireframe shader only works with the Universal Render Pipeline enabled in the project. To enable this in the project go to Project Settings / Graphics and assign the [UniversalRenderPipelineAsset](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/Shaders/URP/UniversalRenderPipelineAsset.asset) to the Scriptable Render Pipeline Settings field. Also see https://github.com/Unity-Technologies/arfoundation-demos#disclaimer
