### ISSUE TITLE
how can i get timestamp of the pose

### ISSUE THREAD

**Issue by ar4ds** [Unity-Technologies/arfoundation-demos#40]
we need the accuracy timestamp of the current pose, thanks

**Comment by DanMillerDev** [comment]
Hi, I'm not sure what pose you're referencing and if this relates to a demo in this project or AR Foundation in general.

ARKit runs at 60 frames per second

ARCore runs at 30 frames per second on most devices and 60 frames per second on some supported devices.

**Comment by DanMillerDev** [comment]
closing since there wasn't further clarification
