### ISSUE TITLE
Occlusion is not working properly

### ISSUE THREAD

**Issue by Abdelkareem-dev** [Unity-Technologies/arfoundation-demos#41]
Hi everyone,

I used Occlusion shader from ARfoundation samples and added occlusion material to ARPlane prefab additionally to default PlaneMat.
It is working fine when detecting surfaces the high surface hides the lower one but when I place an object, the high surface does not hide the object.

**Comment by DanMillerDev** [comment]
Hi, there isn't an occlusion shader in this repo if you're having issues with the occlusion shader in the arfoundation samples repo I suggest opening an issue there https://github.com/Unity-Technologies/arfoundation-samples/issues
