### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ManChrys** [Unity-Technologies/arfoundation-demos#42]
Hello and happy new year .

I want to use AR Foundation Demo — Onboarding UX simple AR on an app that i have built on android. Is this demo only for IOS? 

Thanks in advance.

**Comment by DanMillerDev** [comment]
The demo works for iOS (ARkit) and Android (ARCore). The only demos / features restricted to iOS (ARKit) is the meshing placement since it uses the classification API on LiDAR enabled devices and the camera grain shader since it uses the camera grain rendering feature only available in ARKit.

**Comment by ManChrys** [comment]
Hello,

i have 2 questions.

1)On ArSession there is a script which called AR Kit Overcoaching Overlay. And on ScreenSpaceUI, on AUX Animation Manager (script) there is Coaching overlay where you place the previous AR Kit Overcoaching Overlay. This is for IOS right ?
 So i dont have to use it for Arcore

![1](https://user-images.githubusercontent.com/67521662/103945981-b4519600-513e-11eb-8fb0-5fe87c3327d2.png)
![2](https://user-images.githubusercontent.com/67521662/103945986-b582c300-513e-11eb-95f5-5558d787c58b.png)

2)when im running the app my AR Camera doesnt work because i  have black screen and keep saying "wait for tracking to begin"

Sorry for my noob questions but im new on AR and  unity generally.

Thanks in advance.
