### ISSUE TITLE
AR Foundation Demos — Onboarding UX

### ISSUE THREAD

**Issue by ManChrys** [Unity-Technologies/arfoundation-demos#43]
Hello,

i have 2 questions.

1)On ArSession there is a script which called AR Kit Overcoaching Overlay. And on ScreenSpaceUI, on AUX Animation Manager (script) there is Coaching overlay where you place the previous AR Kit Overcoaching Overlay. This is for IOS right ?
 So i dont have to use it for Arcore

![1](https://user-images.githubusercontent.com/67521662/103945981-b4519600-513e-11eb-8fb0-5fe87c3327d2.png)
![2](https://user-images.githubusercontent.com/67521662/103945986-b582c300-513e-11eb-95f5-5558d787c58b.png)

2)when im running the app my AR Camera doesnt work because i  have black screen and keep saying "wait for tracking to begin"

![3](https://user-images.githubusercontent.com/67521662/103946755-b5cf8e00-513f-11eb-9034-7b87c6994fc2.png)

Sorry for my noob questions but im new on AR and  unity generally.

Thanks in advance.

_Originally posted by @ManChrys in https://github.com/Unity-Technologies/arfoundation-demos/issues/42#issuecomment-756393694_

**Comment by ManChrys** [comment]
ok i fix this.

Thank you.

**Comment by laurencecliffe** [comment]
HI there, I currently have the same problem. Do you remember how you fixed this?

**Comment by ManChrys** [comment]
> HI there, I currently have the same problem. Do you remember how you fixed this?

you can give a try to my project which is in my repo. I used UX for android.

**Comment by ManChrys** [comment]
> > HI there, I currently have the same problem. Do you remember how you fixed this?

Hello my friend,
i dont remember now what i did but you can git my repo where is the fixed one.

**Comment by FarahSibtain** [comment]
I had the same issue in my application when I upgraded ARFoundtion from 3.x to 4.x, resolved it simply by turning on ARCore from project settings.
![image](https://user-images.githubusercontent.com/71545813/123218103-bf2d9680-d4e4-11eb-9398-8ce5751db504.png)

**Comment by pinnakkkk** [comment]
> Hello,
> 
> i have 2 questions.
> 
> 1)On ArSession there is a script which called AR Kit Overcoaching Overlay. And on ScreenSpaceUI, on AUX Animation Manager (script) there is Coaching overlay where you place the previous AR Kit Overcoaching Overlay. This is for IOS right ?
> So i dont have to use it for Arcore
> 
> ![1](https://user-images.githubusercontent.com/67521662/103945981-b4519600-513e-11eb-8fb0-5fe87c3327d2.png)
> ![2](https://user-images.githubusercontent.com/67521662/103945986-b582c300-513e-11eb-95f5-5558d787c58b.png)
> 
> 2)when im running the app my AR Camera doesnt work because i have black screen and keep saying "wait for tracking to begin"
> 
> ![3](https://user-images.githubusercontent.com/67521662/103946755-b5cf8e00-513f-11eb-9034-7b87c6994fc2.png)
> 
> Sorry for my noob questions but im new on AR and unity generally.
> 
> Thanks in advance.
> 
> _Originally posted by @ManChrys in [#42 (comment)](https://github.com/Unity-Technologies/arfoundation-demos/issues/42#issuecomment-756393694)_

could you send me that asset it's removed from unity asset store

**Comment by ManChrys** [comment]
@pinnakkkk do you want to use it for Android or iOS app ?

**Comment by ManChrys** [comment]
you can try to git my repo. I fixed that.
