### ISSUE TITLE
Prevent the real object while plane tracking

### ISSUE THREAD

**Issue by Pankaj68** [Unity-Technologies/arfoundation-demos#48]
Hi

how can i prevent the real object while the plane tracking. if i am tracking the plane (Both Vertical and horizontal) then real object like Laptop, Chair ,TV and AC on this object the plane will not draw but it will draw plane around them 
i am attaching the the reference video so you can understand what i mean to say.

https://user-images.githubusercontent.com/82649539/115010652-477f3200-9ecb-11eb-9df5-24253015620c.mov

**Comment by DanMillerDev** [comment]
This requires a custom computer vision solution for recognizing and detecting the edge of those objects and then cutting them out from the plane shader. This isn't a relevant issue with this repo, I recommend asking the question on the AR forums https://forum.unity.com/forums/ar.161/
