### ISSUE TITLE
Where is MeshVisualization scene in the latest master?

### ISSUE THREAD

**Issue by dzak83** [Unity-Technologies/arfoundation-demos#49]
In the main page doc MeshVisualization is mentioned as something we can try to see mesh visualization. However I don't see it anymore in master.

Can you please update the doc and point us to the new place?

**Comment by DanMillerDev** [comment]
I've updated the documentation, the scene can be found here https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/Shaders/Wireframe/Scenes/MeshVisualization.unity

Thank you for the report.
