### ISSUE TITLE
Found a potential typo in ImageTracking demo's code

### ISSUE THREAD

**Issue by Kyle0936** [Unity-Technologies/arfoundation-demos#51]
[ImageTrackingObjectManager.cs](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/ImageTracking/Scripts/ImageTrackingObjectManager.cs)

Found a potential typo on line 158: `else if (image.referenceImage.guid == s_FirstImageGUID)`

It should be `else if (image.referenceImage.guid == s_SecondImageGUID)` to match the second image's guid instead of the first image's.

**Comment by DanMillerDev** [comment]
Good catch, thanks for the report. I've changed the line and pushed an update. https://github.com/Unity-Technologies/arfoundation-demos/commit/e621654cf94bdc4f012693a1573c74434eb8d0d8
