### ISSUE TITLE
Meshing is not working in below iPhone 12 Pro & Android ARCore supported devices

### ISSUE THREAD

**Issue by jayesh8585** [Unity-Technologies/arfoundation-demos#52]
I have checked that meshing is not working on android ARCore supported devices & below iPhone 12 pro
Is there any settings ?

**Comment by Surbhidhingra** [comment]
Hi, did you find solution to get the meshing scene working on iPad pro

**Comment by DanMillerDev** [comment]
Meshing is only supported on LiDAR enabled devices with ARkit. I've added a disclaimer to the readme. Thanks for reporting.
